#!/usr/bin/env ruby

NODE_BIN = "./node_modules/.bin"

DIST_BUNDLE = "dist/bundle/dashjs-p2p-bundle.js"

`mkdir -p dist`
`mkdir -p dist/bundle`
system("#{NODE_BIN}/browserify -p browserify-derequire -t [babelify] -s DashjsP2PBundle lib/DashjsBundle.js | uglifyjs -m --compress warnings=false,drop_console=true > #{DIST_BUNDLE}")
